faz_dic:
    root_link : "https://www.faz.net"
    topic_link : lay-MegaMenu_SectionTitleLink
    article_link: js-hlp-LinkSwap js-tsr-Base_ContentLink tsr-Base_ContentLink

faz_base_parser:
    time:
        id : time
        keyword : atc-MetaTime
        parse_attr: False
    headline:
        id : span
        keyword : atc-HeadlineText
        parse_attr: False
    headline_emphasis:
        id : span
        keyword : atc-HeadlineEmphasisText
        parse_attr: False
    author:
        id : spaan
        keyword : atc-MetaAuthorLink
        parse_attr: False
    comments:
        id : ul
        keyword: ctn-PageFunctions_List js-sharebuttons
        attribute: data-comment-value
        parse_attr: True    
    recommendation: 
        id : ul
        keyword: ctn-PageFunctions_List js-sharebuttons
        attribute: data-empfehlen-value
        parse_attr: True
 